# Generated by Django 5.2.4 on 2025-07-18 00:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CampoDisponible",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100, unique=True)),
                (
                    "tipo_dato",
                    models.CharField(
                        choices=[
                            ("texto", "Texto"),
                            ("fecha", "Fecha"),
                            ("numero", "Número"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentoSubido",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_original", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("imagen", "Imagen"),
                            ("texto", "Texto"),
                        ],
                        max_length=10,
                    ),
                ),
                ("archivo_url", models.CharField(max_length=500)),
                (
                    "fecha_subida",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlantillaDocumento",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True)),
                ("html_con_campos", models.TextField()),
                (
                    "fecha_creacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentoGenerado",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("datos_rellenados", models.JSONField()),
                ("html_resultante", models.TextField()),
                (
                    "fecha_generacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "plantilla",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documentos.plantilladocumento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CampoPlantilla",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_variable", models.CharField(max_length=100)),
                (
                    "campo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documentos.campodisponible",
                    ),
                ),
                (
                    "plantilla",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campos_asociados",
                        to="documentos.plantilladocumento",
                    ),
                ),
            ],
        ),
    ]
