# Generated by Django 5.2.4 on 2025-07-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentosubido",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF"),
                    ("imagen", "Imagen"),
                    ("texto", "Texto"),
                    ("word", "Docx"),
                ],
                max_length=10,
            ),
        ),
    ]
