# Generated by Django 5.2.4 on 2025-07-20 01:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0002_alter_documentosubido_tipo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FavoritoPlantilla",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "fecha_agregado",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "plantilla",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documentos.plantilladocumento",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("usuario", "plantilla")},
            },
        ),
    ]
