# Generated by Django 5.2.4 on 2025-07-20 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0003_favoritoplantilla"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoPlantillaDocumento",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="plantilladocumento",
            name="tipo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="documentos.tipoplantilladocumento",
            ),
        ),
    ]
