# Generated by Django 5.2.4 on 2025-07-20 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0004_tipoplantilladocumento_plantilladocumento_tipo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantillaCompartida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permisos",
                    models.CharField(
                        choices=[
                            ("lectura", "Solo lectura"),
                            ("edicion", "Lectura y edición"),
                        ],
                        default="lectura",
                        max_length=20,
                    ),
                ),
                ("fecha_compartida", models.DateTimeField(auto_now_add=True)),
                (
                    "plantilla",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compartidas",
                        to="documentos.plantilladocumento",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plantillas_compartidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("plantilla", "usuario")},
            },
        ),
    ]
