# Generated by Django 5.2.4 on 2025-07-07 20:40

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Clasificacion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=200)),
                ("fechaCreacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Clasificacion",
                "db_table": "clasificacion",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Empresas",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("rut", models.CharField(max_length=15)),
                ("nombre", models.CharField(max_length=250)),
                ("correo", models.CharField(max_length=250)),
                ("fechaCreacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Empresas",
                "db_table": "empresas",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Perfiles",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=250)),
                ("entidad", models.CharField(max_length=250)),
                ("rutEntidad", models.CharField(max_length=15)),
                ("representante", models.CharField(max_length=250)),
                ("rutRepresentante", models.CharField(max_length=15)),
                ("mandato", models.CharField(max_length=1000)),
                (
                    "informacion",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("descripcion", models.CharField(max_length=1000)),
                ("header", models.CharField(blank=True, max_length=1000, null=True)),
                ("footer", models.CharField(blank=True, max_length=1000, null=True)),
                ("fechaCreacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Perfiles",
                "db_table": "perfiles",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Planes",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("tipoPlan", models.CharField(max_length=200)),
                ("nombre", models.CharField(max_length=200)),
                ("precio", models.FloatField()),
                ("cantidadUsers", models.IntegerField(default=1)),
                ("cantidadEscritos", models.IntegerField(default=1)),
                ("cantidadDemandas", models.IntegerField(default=1)),
                ("cantidadContratos", models.IntegerField(default=1)),
                ("cantidadConsultas", models.IntegerField(default=1)),
                ("fechaCreacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Planes",
                "db_table": "planes",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="TipoDocumento",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=200)),
                ("fechaCreacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Tipo de Documento",
                "db_table": "tipo_documento",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Tribunales",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=250)),
                ("fechaCreacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Tribunales",
                "db_table": "tribunales",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Usuarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.empresas",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Usuarios",
                "db_table": "usuarios",
                "managed": True,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Documentos",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=200)),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("plantilla", models.FileField(blank=True, null=True, upload_to="")),
                ("campos", models.JSONField(blank=True, null=True)),
                ("version", models.IntegerField(default=1)),
                ("fechaCreacion", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tipoDocumento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.tipodocumento",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Documentos",
                "db_table": "documentos",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Compartir",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fechaCreacion", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usuario",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuarios",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.documentos"
                    ),
                ),
                ("empresas", models.ManyToManyField(blank=True, to="api.empresas")),
            ],
            options={
                "verbose_name_plural": "Compartir",
                "db_table": "compartir",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Favoritos",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fechaCreacion", models.DateTimeField(auto_now_add=True)),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.documentos"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Favoritos",
                "db_table": "favoritos",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="empresas",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.planes"
            ),
        ),
        migrations.CreateModel(
            name="Plantillas",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=200)),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("fechaCreacion", models.DateTimeField(auto_now_add=True)),
                (
                    "clasificacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.clasificacion",
                    ),
                ),
                ("documentos", models.ManyToManyField(blank=True, to="api.documentos")),
            ],
            options={
                "verbose_name_plural": "Plantillas",
                "db_table": "plantillas",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Escritos",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("rol", models.CharField(blank=True, max_length=100, null=True)),
                ("fechaCreacion", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.documentos"
                    ),
                ),
                (
                    "tribunales",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.tribunales"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Escritos",
                "db_table": "escritos",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Demandas",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("operacion", models.CharField(blank=True, max_length=100, null=True)),
                ("fechaCreacion", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.documentos"
                    ),
                ),
                (
                    "tribunales",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.tribunales"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Demandas",
                "db_table": "demandas",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Contratos",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fechaCreacion", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.documentos"
                    ),
                ),
                (
                    "tribunales",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.tribunales"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Contratos",
                "db_table": "contratos",
                "managed": True,
            },
        ),
    ]
