# Generated by Django 5.2.4 on 2025-07-08 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_empresas_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresas",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.planes"
            ),
        ),
    ]
