services:
  # Database Service (PostgreSQL)
  postgres:
    image: postgres:17.4-alpine3.21
    container_name: backend
    restart: on-failure
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=jcmalco
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=legal
    ports:
      - "5432:5432"
    #volumes:
    #  - postgres_data:/var/lib/postgresql/data
    #networks:
    #  - my_network

  # Backend Service (API with python and django)
  api:
    build: .
    container_name: api
    restart: on-failure
    depends_on:
      - postgres
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "
        python manage.py runserver 0.0.0.0:8000
      "

  # pgAdmin Service (PostgreSQL Web Interface)
  pgadmin:
    image: dpage/pgadmin4:latest # Uses the official pgAdmin 4 image
    depends_on:
      - postgres
    ports:
      - "5050:80" # Map host port 5050 to pgAdmin container port 80
    environment:
      PGADMIN_DEFAULT_EMAIL: "jcmalco@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
      #PGADMIN_LISTEN_PORT: 80 # Explicitly set for clarity
    #volumes:
      # Changed to bind mount to a local 'datastore/pgadmin_data' folder
     # - pgadmin_data:/var/lib/pgadmin