# Generated by Django 5.2.4 on 2025-07-31 01:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CampoDisponible",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100, unique=True)),
                (
                    "tipo_dato",
                    models.CharField(
                        choices=[
                            ("texto", "Texto"),
                            ("fecha", "Fecha"),
                            ("numero", "Número"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Campos Disponibles",
                "db_table": "campos_disponibles",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ClasificacionPlantillaGeneral",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=200)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Clasificacion Plantilla General",
                "db_table": "clasificacion_plantilla_general",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="TipoPlantillaDocumento",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name_plural": "Tipos de Plantillas",
                "db_table": "tipos_plantillas",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="DocumentoSubido",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_original", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("imagen", "Imagen"),
                            ("texto", "Texto"),
                            ("word", "Docx"),
                        ],
                        max_length=10,
                    ),
                ),
                ("archivo_url", models.CharField(max_length=500)),
                (
                    "fecha_subida",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Documentos Subidos",
                "db_table": "documentos_subidos",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="PlantillaDocumento",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True)),
                ("html_con_campos", models.TextField()),
                (
                    "fecha_creacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="documents.tipoplantilladocumento",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Plantillas de Documentos",
                "db_table": "plantillas_documentos",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="DocumentoGenerado",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("datos_rellenados", models.JSONField()),
                ("html_resultante", models.TextField()),
                (
                    "fecha_generacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plantilla",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.plantilladocumento",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Documentos Generados",
                "db_table": "documentos_generados",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="CampoPlantilla",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_variable", models.CharField(max_length=100)),
                (
                    "campo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.campodisponible",
                    ),
                ),
                (
                    "plantilla",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campos_asociados",
                        to="documents.plantilladocumento",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Campos de Plantillas",
                "db_table": "campos_plantillas",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="PlantillaGeneral",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=200)),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "clasificacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.clasificacionplantillageneral",
                    ),
                ),
                (
                    "documentos",
                    models.ManyToManyField(
                        blank=True, to="documents.plantilladocumento"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Plantillas Generales",
                "db_table": "plantillas_generales",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="PlantillaCompartida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permisos",
                    models.CharField(
                        choices=[
                            ("lectura", "Solo lectura"),
                            ("edicion", "Lectura y edición"),
                        ],
                        default="lectura",
                        max_length=20,
                    ),
                ),
                ("fecha_compartida", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plantillas_compartidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plantilla",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compartidas",
                        to="documents.plantilladocumento",
                    ),
                ),
            ],
            options={
                "unique_together": {("plantilla", "usuario")},
            },
        ),
        migrations.CreateModel(
            name="PlantillaFavorita",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "fecha_agregado",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "plantilla",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.plantilladocumento",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("usuario", "plantilla")},
            },
        ),
    ]
