# Generated by Django 5.2.4 on 2025-07-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Clasificacion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=200)),
                ("fechaCreacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Clasificacion",
                "db_table": "clasificacion",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Contratos",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fechaCreacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Contratos",
                "db_table": "contratos",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Demandas",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("operacion", models.CharField(blank=True, max_length=100, null=True)),
                ("fechaCreacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Demandas",
                "db_table": "demandas",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Documentos",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=200)),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("plantilla", models.FileField(blank=True, null=True, upload_to="")),
                ("campos", models.JSONField(blank=True, null=True)),
                ("version", models.IntegerField(default=1)),
                ("fechaCreacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Documentos",
                "db_table": "documentos",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Escritos",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("rol", models.CharField(blank=True, max_length=100, null=True)),
                ("fechaCreacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Escritos",
                "db_table": "escritos",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Favoritos",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fechaCreacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Favoritos",
                "db_table": "favoritos",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Plantillas",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=200)),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("fechaCreacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Plantillas",
                "db_table": "plantillas",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="TipoDocumento",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=200)),
                ("fechaCreacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Tipo de Documento",
                "db_table": "tipo_documento",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Tribunales",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=250)),
                ("fechaCreacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Tribunales",
                "db_table": "tribunales",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Compartir",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fechaCreacion", models.DateTimeField(auto_now_add=True)),
                (
                    "empresas",
                    models.ManyToManyField(blank=True, to="companies.empresas"),
                ),
            ],
            options={
                "verbose_name_plural": "Compartir",
                "db_table": "compartir",
                "managed": True,
            },
        ),
    ]
