# Generated by Django 5.2.4 on 2025-08-03 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantillaGeneralCompartida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_asignacion", models.DateTimeField(auto_now_add=True)),
                (
                    "fecha_expiracion",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha de expiración del acceso al paquete",
                        null=True,
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True, help_text="Si la asignación está activa"
                    ),
                ),
                (
                    "notas",
                    models.TextField(
                        blank=True,
                        help_text="Notas sobre por qué se asignó este paquete",
                        null=True,
                    ),
                ),
                (
                    "fecha_ultimo_acceso",
                    models.DateTimeField(
                        blank=True,
                        help_text="Última vez que el usuario accedió a plantillas de este paquete",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignación de Paquete de Plantillas",
                "verbose_name_plural": "Asignaciones de Paquetes de Plantillas",
                "db_table": "documents_plantillageneralcompartida",
            },
        ),
        migrations.AlterModelOptions(
            name="clasificacionplantillageneral",
            options={
                "managed": True,
                "ordering": ["nombre"],
                "verbose_name": "Categoría de Paquetes",
                "verbose_name_plural": "Categorías de Paquetes",
            },
        ),
        migrations.AlterModelOptions(
            name="plantillageneral",
            options={
                "managed": True,
                "ordering": ["nombre"],
                "verbose_name": "Paquete de Plantillas",
                "verbose_name_plural": "Paquetes de Plantillas",
            },
        ),
        migrations.RemoveField(
            model_name="plantillageneral",
            name="documentos",
        ),
        migrations.AddField(
            model_name="clasificacionplantillageneral",
            name="creado_por",
            field=models.ForeignKey(
                default=0,
                help_text="Administrador que creó esta clasificación",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clasificaciones_paquetes_creadas",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clasificacionplantillageneral",
            name="descripcion",
            field=models.TextField(
                blank=True,
                help_text="Descripción de qué tipo de paquetes incluye esta categoría",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="clasificacionplantillageneral",
            name="fecha_actualizacion",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="plantillageneral",
            name="activo",
            field=models.BooleanField(
                default=True, help_text="Si el paquete está disponible para asignar"
            ),
        ),
        migrations.AddField(
            model_name="plantillageneral",
            name="creado_por_admin",
            field=models.ForeignKey(
                default=1,
                help_text="Administrador que creó este paquete",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paquetes_plantillas_creados",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plantillageneral",
            name="es_paquete_premium",
            field=models.BooleanField(
                default=False,
                help_text="Si es un paquete premium con plantillas especiales",
            ),
        ),
        migrations.AddField(
            model_name="plantillageneral",
            name="fecha_actualizacion",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="plantillageneral",
            name="plantillas_incluidas",
            field=models.ManyToManyField(
                blank=True,
                help_text="Plantillas de documento incluidas en este paquete",
                related_name="paquetes_que_la_incluyen",
                to="documents.plantilladocumento",
            ),
        ),
        migrations.AlterField(
            model_name="clasificacionplantillageneral",
            name="nombre",
            field=models.CharField(
                help_text="Nombre de la categoría (ej: 'Contratos Comerciales')",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="plantillageneral",
            name="descripcion",
            field=models.TextField(
                blank=True,
                help_text="Descripción del paquete y qué plantillas incluye",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="plantillageneral",
            name="nombre",
            field=models.CharField(
                help_text="Nombre del paquete de plantillas", max_length=200
            ),
        ),
        migrations.AddIndex(
            model_name="clasificacionplantillageneral",
            index=models.Index(
                fields=["creado_por"], name="clasificaci_creado__73b053_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plantillageneral",
            index=models.Index(fields=["activo"], name="plantillas__activo_da4e47_idx"),
        ),
        migrations.AddIndex(
            model_name="plantillageneral",
            index=models.Index(
                fields=["creado_por_admin"], name="plantillas__creado__849e12_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plantillageneral",
            index=models.Index(
                fields=["clasificacion", "activo"],
                name="plantillas__clasifi_482ebd_idx",
            ),
        ),
        migrations.AddField(
            model_name="plantillageneralcompartida",
            name="asignado_por",
            field=models.ForeignKey(
                help_text="Administrador que asignó este paquete",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paquetes_plantillas_asignados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="plantillageneralcompartida",
            name="plantilla_general",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asignaciones",
                to="documents.plantillageneral",
            ),
        ),
        migrations.AddField(
            model_name="plantillageneralcompartida",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plantillas_generales_asignadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="plantillageneralcompartida",
            index=models.Index(
                fields=["plantilla_general", "usuario", "activo"],
                name="documents_p_plantil_59ba8e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="plantillageneralcompartida",
            index=models.Index(
                fields=["fecha_expiracion"], name="documents_p_fecha_e_c61cdf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plantillageneralcompartida",
            index=models.Index(
                fields=["asignado_por"], name="documents_p_asignad_063865_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="plantillageneralcompartida",
            unique_together={("plantilla_general", "usuario")},
        ),
    ]
