# Generated by Django 5.2.4 on 2025-07-13 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="compartir",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usuario",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="compartir",
            name="usuarios",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="contratos",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="contratos",
            name="tribunales",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="companies.tribunales"
            ),
        ),
        migrations.AddField(
            model_name="demandas",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="demandas",
            name="tribunales",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="companies.tribunales"
            ),
        ),
        migrations.AddField(
            model_name="documentos",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="documentos",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="demandas",
            name="documento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="documents.documentos"
            ),
        ),
        migrations.AddField(
            model_name="contratos",
            name="documento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="documents.documentos"
            ),
        ),
        migrations.AddField(
            model_name="compartir",
            name="documento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="documents.documentos"
            ),
        ),
        migrations.AddField(
            model_name="escritos",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="escritos",
            name="documento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="documents.documentos"
            ),
        ),
        migrations.AddField(
            model_name="escritos",
            name="tribunales",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="companies.tribunales"
            ),
        ),
        migrations.AddField(
            model_name="favoritos",
            name="documento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="documents.documentos"
            ),
        ),
        migrations.AddField(
            model_name="favoritos",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="plantillas",
            name="clasificacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="documents.clasificacion",
            ),
        ),
        migrations.AddField(
            model_name="plantillas",
            name="documentos",
            field=models.ManyToManyField(blank=True, to="documents.documentos"),
        ),
        migrations.AddField(
            model_name="documentos",
            name="tipoDocumento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="documents.tipodocumento",
            ),
        ),
    ]
