# Generated by Django 5.2.4 on 2025-08-07 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_plantillageneralcompartida_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentogenerado",
            name="nombre",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
