# Generated by Django 5.2.4 on 2025-07-27 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_campodisponible_tipoplantilladocumento_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClasificacionPlantillaGeneral",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=200)),
                ("fechaCreacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Clasificacion Plantilla General",
                "db_table": "clasificacion_plantilla_general",
                "managed": True,
            },
        ),
        migrations.RemoveField(
            model_name="plantillas",
            name="clasificacion",
        ),
        migrations.RemoveField(
            model_name="compartir",
            name="documento",
        ),
        migrations.RemoveField(
            model_name="compartir",
            name="empresas",
        ),
        migrations.RemoveField(
            model_name="compartir",
            name="usuario",
        ),
        migrations.RemoveField(
            model_name="compartir",
            name="usuarios",
        ),
        migrations.RemoveField(
            model_name="contratos",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="contratos",
            name="documento",
        ),
        migrations.RemoveField(
            model_name="contratos",
            name="tribunales",
        ),
        migrations.RemoveField(
            model_name="demandas",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="demandas",
            name="documento",
        ),
        migrations.RemoveField(
            model_name="demandas",
            name="tribunales",
        ),
        migrations.RemoveField(
            model_name="documentos",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="documentos",
            name="tipoDocumento",
        ),
        migrations.RemoveField(
            model_name="documentos",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="escritos",
            name="documento",
        ),
        migrations.RemoveField(
            model_name="favoritos",
            name="documento",
        ),
        migrations.RemoveField(
            model_name="plantillas",
            name="documentos",
        ),
        migrations.RemoveField(
            model_name="escritos",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="escritos",
            name="tribunales",
        ),
        migrations.RemoveField(
            model_name="favoritos",
            name="usuario",
        ),
        migrations.CreateModel(
            name="PlantillaGeneral",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=200)),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("fechaCreacion", models.DateTimeField(auto_now_add=True)),
                (
                    "clasificacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.clasificacionplantillageneral",
                    ),
                ),
                (
                    "documentos",
                    models.ManyToManyField(
                        blank=True, to="documents.plantilladocumento"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Plantillas Generales",
                "db_table": "plantillas_generales",
                "managed": True,
            },
        ),
        migrations.DeleteModel(
            name="Clasificacion",
        ),
        migrations.DeleteModel(
            name="Compartir",
        ),
        migrations.DeleteModel(
            name="Contratos",
        ),
        migrations.DeleteModel(
            name="Demandas",
        ),
        migrations.DeleteModel(
            name="TipoDocumento",
        ),
        migrations.DeleteModel(
            name="Documentos",
        ),
        migrations.DeleteModel(
            name="Plantillas",
        ),
        migrations.DeleteModel(
            name="Escritos",
        ),
        migrations.DeleteModel(
            name="Favoritos",
        ),
    ]
