# Generated by Django 5.2.4 on 2025-08-07 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_documentogenerado_nombre"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plantillacompartida",
            options={"managed": True, "verbose_name_plural": "Plantillas Compartidas"},
        ),
        migrations.AlterModelOptions(
            name="plantillafavorita",
            options={"managed": True, "verbose_name_plural": "Plantillas Favoritas"},
        ),
        migrations.RenameIndex(
            model_name="clasificacionplantillageneral",
            new_name="clasificaci_creado__c46623_idx",
            old_name="clasificaci_creado__73b053_idx",
        ),
        migrations.RenameIndex(
            model_name="plantillageneralcompartida",
            new_name="plantillas__plantil_356652_idx",
            old_name="documents_p_plantil_59ba8e_idx",
        ),
        migrations.RenameIndex(
            model_name="plantillageneralcompartida",
            new_name="plantillas__fecha_e_645977_idx",
            old_name="documents_p_fecha_e_c61cdf_idx",
        ),
        migrations.RenameIndex(
            model_name="plantillageneralcompartida",
            new_name="plantillas__asignad_a65e36_idx",
            old_name="documents_p_asignad_063865_idx",
        ),
        migrations.AlterModelTable(
            name="clasificacionplantillageneral",
            table="clasificaciones_plantillas_generales",
        ),
        migrations.AlterModelTable(
            name="plantillacompartida",
            table="plantillas_compartidas",
        ),
        migrations.AlterModelTable(
            name="plantillafavorita",
            table="plantillas_favoritas",
        ),
        migrations.AlterModelTable(
            name="plantillageneralcompartida",
            table="plantillas_generales_compartidas",
        ),
        migrations.AlterModelTable(
            name="tipoplantilladocumento",
            table="tipos_plantillas_documentos",
        ),
    ]
