# Generated by Django 5.2.4 on 2025-08-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_alter_plantillacompartida_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentosubido",
            name="html_con_campos",
            field=models.TextField(blank=True, null=True),
        ),
    ]
