# Generated by Django 5.2.4 on 2025-07-27 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_clasificacionplantillageneral_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campodisponible",
            options={"managed": True, "verbose_name_plural": "Campos Disponibles"},
        ),
        migrations.AlterModelOptions(
            name="campoplantilla",
            options={"managed": True, "verbose_name_plural": "Campos de Plantillas"},
        ),
        migrations.AlterModelOptions(
            name="documentogenerado",
            options={"managed": True, "verbose_name_plural": "Documentos Generados"},
        ),
        migrations.AlterModelOptions(
            name="documentosubido",
            options={"managed": True, "verbose_name_plural": "Documentos Subidos"},
        ),
        migrations.AlterModelOptions(
            name="plantilladocumento",
            options={
                "managed": True,
                "verbose_name_plural": "Plantillas de Documentos",
            },
        ),
        migrations.AlterModelOptions(
            name="tipoplantilladocumento",
            options={"managed": True, "verbose_name_plural": "Tipos de Plantillas"},
        ),
        migrations.AlterModelTable(
            name="campodisponible",
            table="campos_disponibles",
        ),
        migrations.AlterModelTable(
            name="campoplantilla",
            table="campos_plantillas",
        ),
        migrations.AlterModelTable(
            name="documentogenerado",
            table="documentos_generados",
        ),
        migrations.AlterModelTable(
            name="documentosubido",
            table="documentos_subidos",
        ),
        migrations.AlterModelTable(
            name="plantilladocumento",
            table="plantillas_documentos",
        ),
        migrations.AlterModelTable(
            name="tipoplantilladocumento",
            table="tipos_plantillas",
        ),
    ]
