# Generated by Django 5.2.4 on 2025-07-27 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0005_alter_campodisponible_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clasificacionplantillageneral",
            old_name="fechaCreacion",
            new_name="fecha_creacion",
        ),
        migrations.RenameField(
            model_name="plantillageneral",
            old_name="fechaCreacion",
            new_name="fecha_creacion",
        ),
    ]
