# Generated by Django 5.2.4 on 2025-08-19 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0005_documentosubido_html_con_campos"),
    ]

    operations = [
        migrations.RenameField(
            model_name="documentosubido",
            old_name="html_con_campos",
            new_name="html",
        ),
    ]
