# Generated by Django 5.2.4 on 2025-08-24 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0006_rename_html_con_campos_documentosubido_html"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaPlantillaDocumento",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name_plural": "Categorias de Plantillas",
                "db_table": "categorias_plantillas_documentos",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="plantilladocumento",
            name="clasificacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="documents.clasificacionplantillageneral",
            ),
        ),
        migrations.AddField(
            model_name="plantilladocumento",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="documents.categoriaplantilladocumento",
            ),
        ),
    ]
