# Generated by Django 5.2.4 on 2025-07-11 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Planes",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("tipoPlan", models.CharField(max_length=200)),
                ("nombre", models.CharField(max_length=200)),
                ("precio", models.FloatField()),
                ("cantidadUsers", models.IntegerField(default=1)),
                ("cantidadEscritos", models.IntegerField(default=1)),
                ("cantidadDemandas", models.IntegerField(default=1)),
                ("cantidadContratos", models.IntegerField(default=1)),
                ("cantidadConsultas", models.IntegerField(default=1)),
                ("fechaCreacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Planes",
                "db_table": "planes",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Empresas",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("rut", models.CharField(max_length=15)),
                ("nombre", models.CharField(max_length=250)),
                ("correo", models.CharField(max_length=250)),
                ("fechaCreacion", models.DateTimeField(auto_now_add=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.planes",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Empresas",
                "db_table": "empresas",
                "managed": True,
            },
        ),
    ]
