# Generated by Django 5.2.4 on 2025-08-07 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="empresas",
            old_name="fechaCreacion",
            new_name="fecha_creacion",
        ),
        migrations.RenameField(
            model_name="planes",
            old_name="fechaCreacion",
            new_name="fecha_creacion",
        ),
        migrations.RenameField(
            model_name="tribunales",
            old_name="fechaCreacion",
            new_name="fecha_creacion",
        ),
    ]
