# Generated by Django 5.2.4 on 2025-08-07 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_rename_fechacreacion_empresas_fecha_creacion_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="planes",
            old_name="cantidadConsultas",
            new_name="cantidad_consultas",
        ),
        migrations.RenameField(
            model_name="planes",
            old_name="cantidadContratos",
            new_name="cantidad_contratos",
        ),
        migrations.RenameField(
            model_name="planes",
            old_name="cantidadDemandas",
            new_name="cantidad_demandas",
        ),
        migrations.RenameField(
            model_name="planes",
            old_name="cantidadEscritos",
            new_name="cantidad_escritos",
        ),
        migrations.RenameField(
            model_name="planes",
            old_name="cantidadUsers",
            new_name="cantidad_users",
        ),
        migrations.RenameField(
            model_name="planes",
            old_name="tipoPlan",
            new_name="tipo_plan",
        ),
    ]
