# Generated by Django 5.2.4 on 2025-08-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuarios",
            name="descargar",
            field=models.CharField(
                choices=[("pdf", "PDF"), ("docx", "DOCX")], default="pdf", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="usuarios",
            name="interlineado",
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=10),
        ),
    ]
