# Generated by Django 5.2.4 on 2025-08-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_usuarios_descargar_usuarios_interlineado"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuarios",
            name="abogado_dos",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="usuarios",
            name="abogado_uno",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="usuarios",
            name="banco",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="usuarios",
            name="footer",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="usuarios",
            name="representante_banco",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="usuarios",
            name="rut_dos",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="usuarios",
            name="rut_representante",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="usuarios",
            name="rut_uno",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
