# Generated by Django 5.2.4 on 2025-08-30 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_usuarios_abogado_dos_usuarios_abogado_uno_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuarios",
            name="abogado_dos",
        ),
        migrations.RemoveField(
            model_name="usuarios",
            name="abogado_uno",
        ),
        migrations.RemoveField(
            model_name="usuarios",
            name="banco",
        ),
        migrations.RemoveField(
            model_name="usuarios",
            name="descargar",
        ),
        migrations.RemoveField(
            model_name="usuarios",
            name="footer",
        ),
        migrations.RemoveField(
            model_name="usuarios",
            name="interlineado",
        ),
        migrations.RemoveField(
            model_name="usuarios",
            name="representante_banco",
        ),
        migrations.RemoveField(
            model_name="usuarios",
            name="rut_dos",
        ),
        migrations.RemoveField(
            model_name="usuarios",
            name="rut_representante",
        ),
        migrations.RemoveField(
            model_name="usuarios",
            name="rut_uno",
        ),
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descargar",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("docx", "DOCX")],
                        default="pdf",
                        max_length=10,
                    ),
                ),
                (
                    "interlineado",
                    models.DecimalField(decimal_places=1, default=1.0, max_digits=10),
                ),
                ("footer", models.TextField(blank=True)),
                ("abogado_uno", models.CharField(blank=True, max_length=100)),
                ("abogado_dos", models.CharField(blank=True, max_length=100)),
                ("rut_uno", models.CharField(blank=True, max_length=100)),
                ("rut_dos", models.CharField(blank=True, max_length=100)),
                ("representante_banco", models.CharField(blank=True, max_length=100)),
                ("rut_representante", models.CharField(blank=True, max_length=100)),
                ("banco", models.CharField(blank=True, max_length=100)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Perfiles",
                "db_table": "perfiles",
                "managed": True,
            },
        ),
    ]
